Documentation:
  Enabled: false

Layout/SpaceBeforeFirstArg:
  Exclude:

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/RescueException:
  Exclude:
    - lib/yaaf/form.rb

Metrics/AbcSize:
  # The ABC size is a calculated magnitude, so this number can be an Integer or
  # a Float.
  Max: 15

Metrics/BlockLength:
  CountComments: false  # count full line comments?
  Max: 25
  Exclude:
    - 'yaaf.gemspec'
    - config/**/*
    - spec/**/*
  ExcludedMethods:
    - class_methods

Metrics/BlockNesting:
  Max: 4

Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200

# Avoid complex methods.
Metrics/CyclomaticComplexity:
  Max: 7

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 24

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200

Metrics/LineLength:
  Max: 100
  # To make it possible to copy or click on URIs in the code, we allow lines
  # containing a URI to be longer than Max.
  AllowURI: true
  URISchemes:
    - http
    - https

Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true

Metrics/PerceivedComplexity:
  Max: 12

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ModuleFunction:
  Enabled: false

Style/RescueModifier:
  Exclude:
    - spec/**/*

Naming/PredicateName:
  Enabled: false
